branch-defaults:
  feature-portfolio:
    environment: null
    group_suffix: null
global:
  application_name: vinceroti.com
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-west-2
  profile: eb-cli
  repository: null
  sc: git
